export interface Incident {
    againstCategoryId: number;
    againstCategoryName: string;
    assignedEmployeeId: number;
    assignedEmployeeName: string;
    assignedEmployeePicUrl: string;
    assignedServiceEngineerId:number;
    assignedServiceEngineerName: string;
    assignedServiceEngineerPicUrl: string;
    lastScheduleDate:string;
    lastModifiedAt:string;
    billNumber: string;
    closedOn:string;
    createdAt: string;
    customerContactNo:string | number;
    customerEmail: string;
    customerId:number;
    customerName: string;
    dealerContact: string;
    dealerName: string;
    description: string;
    id:number;
    isProductVerified:boolean;
    priority: string;
    productBillUrl: string;
    productInstallationDateTime: string;
    productModelNumber: string;
    productBrand:string;
    productName: string;
    productPicUrl:string;
    productPurchaseDate: string;
    productRegistrationId:number | string;
    productWarrantyEnd: string;
    productWarrantyStart: string;
    rca: string;
    reopenCount:number;
    statusColor: string;
    statusId:number;
    statusName: string;
    title: string;
    complaintPicUrl:string;
};